### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by FredHappyface** [belak/base16-schemes#1]
Sorry to raise this as I know that licensing is never a fun topic.

As per the MIT license, you'll need to add the original copyrights into the license file to be compliant with those original licenses. (In all honesty, I'd be surprised if the original authors are hugely bothered but it's worth doing just incase)

Thanks for your time

**Comment by belak** [comment]
Good call, it's on my to-do list, but slipped my mind last night. Thanks for the reminder.
